repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.6
    hooks:
      - id: terraform_fmt
        name: Terraform fmt
        description: Format Terraform files

      - id: terraform_validate
        name: Terraform validate
        description: Validate Terraform configuration

      - id: terraform_docs
        name: Terraform docs
        description: Generate Terraform documentation
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true

      - id: terraform_tflint
        name: Terraform lint
        description: Lint Terraform files with tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace

      - id: end-of-file-fixer
        name: Fix end of files

      - id: check-yaml
        name: Check YAML syntax
        args: ['--unsafe']

      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=500']

      - id: check-merge-conflict
        name: Check for merge conflicts

      - id: detect-private-key
        name: Detect private keys
